#ifndef GAMEWORLD_H
#define GAMEWORLD_H

#include "core/Types.h"
#include "core/FogOfWar.h"
#include "ai/Controller.h"
#include "core/GameCommand.h"
#include "core/GameSnapshot.h"
#include "core/CampaignGeneration.h"
#include "simulation/MapGenerator.h"
#include "economy/Player.h"
#include "ui/Renderer.h"
#include "world/GlobalMap.h"
#include "world/ColonizationDefinition.h"
#include "world/ScoutExpeditionService.h"
#include "world/PlayerState.h"
#include "world/ProvinceSimulation.h"
#include "world/Trade.h"
#include "warfare/BattleLifecycle.h"
#include "world/WorldEventSystem.h"
#include "warfare/WarfareViews.h"

#include <cstdint>

enum class BuildPaymentPolicy
{
    ChargeAuthoritativeCost,
    FreeDebugHuman
};

enum class ColonizationPhase : std::uint8_t
{
    Traveling,
    Establishing,
    Completed,
    Failed
};

struct ColonizationProgressView
{
    ColonizationPhase phase{ColonizationPhase::Traveling};
    float progress{0.0f};
    std::uint64_t remainingTicks{0};
};

enum class WorldLayoutFailure
{
    None,
    InvalidPlayerCount,
    InvalidAnchors,
    MissingStartingVillagePlan,
    InternalError
};

#include <deque>
#include <functional>
#include <iosfwd>
#include <optional>
#include <string_view>
#include <utility>
#include <vector>

class PlayerHandler
{
    public:
        PlayerHandler() = default;

        // Owns all players participating in the current world.
        std::map<int, std::unique_ptr<Player>> players;
};

// Owns the playable simulation state, including map, players and persistence.
class GameWorld
{
    public:
        GameWorld() = default;
        GameWorld(const GameWorld&) = delete;
        GameWorld& operator=(const GameWorld&) = delete;
        GameWorld(GameWorld&&) noexcept = default;
        GameWorld& operator=(GameWorld&&) noexcept = default;

        // Creates a new world with generated terrain and starting entities.
        // Returns false when bounded world generation cannot produce a valid
        // layout. In that case no playable session is started.
        using GenerationProgressCallback = std::function<void(float, const std::string&)>;
        bool InitWorld(std::string, Renderer*, MapParameters params = {},
                       const GenerationProgressCallback& progress = {});
        bool InitWorld(std::string, Renderer*, CampaignGenerationParameters params,
                       const GenerationProgressCallback& progress = {});
        // Creates a deterministic multiplayer world with server-assigned player slots.
        bool InitMultiplayerWorld(std::string name, Renderer* renderer, MapParameters params,
                                  int localPlayerId,
                                  bool authoritativeHost,
                                  const GenerationProgressCallback& progress = {});
        bool InitMultiplayerWorld(std::string name, Renderer* renderer,
                                  CampaignGenerationParameters params, int localPlayerId,
                                  bool authoritativeHost,
                                  const GenerationProgressCallback& progress = {});
        // Binds main-thread presentation services after CPU-only background
        // generation and centers the camera on the local headquarters.
        void AttachPresentation(Renderer* renderer);
        // Writes the current world state to a save file.
        bool SaveToFile(const std::string& path) const;
        // Rebuilds the world state from a save file.
        bool LoadFromFile(const std::string& path, Renderer* renderer);
        // Canonical full simulation state used by multiplayer initial sync and
        // recovery. Unlike GameSnapshot, this includes gameplay state rather
        // than only render data.
        std::string SerializeSimulationState() const;
        // Restores a state emitted by SerializeSimulationState. The optional
        // local-player override keeps the receiving client's UI/controller
        // ownership local while retaining the host's authoritative world.
        bool RestoreSimulationState(std::string_view payload, int localPlayerIdOverride = -1);
        // Queues an intent generated by a human, AI or remote player.
        std::uint64_t SubmitCommand(const GameCommand& command);
        // Queues an intent and assigns an authoritative target tick when needed.
        std::uint64_t SubmitCommand(const GameCommand& command, std::uint64_t minimumTargetTick);
        // Returns command accept/reject results emitted since the last consume.
        std::vector<GameCommandResult> ConsumeCommandResults();
        // Applies a command received from an authoritative host to a client-side mirror.
        bool ApplyAuthoritativeCommand(const GameCommand& command);
        // Advances the simulation by elapsed time in seconds.
        void Update(double);
        // Advances only authoritative gameplay state, without touching visual layers.
        void UpdateSimulation(double dt);
        // Draws terrain, roads, buildings and territory overlays.
        void DrawMap();
        // Captures render-safe world state for another thread.
        GameSnapshot BuildSnapshot() const;
        // Computes a deterministic low-cost gameplay checksum for mirror validation.
        std::uint64_t BuildChecksum() const;
        GlobalMap& GetGlobalMap() { return globalMap; }
        const GlobalMap& GetGlobalMap() const { return globalMap; }
        const CampaignGenerationParameters& GetCampaignGenerationParameters() const
        {
            return campaignGenerationParameters;
        }
        GlobalMapView BuildGlobalMapViewFor(PlayerId playerId) const
        {
            return globalMap.BuildViewFor(playerId);
        }
        ProvinceId GetPlayerProvinceId(PlayerId playerId) const
        {
            const auto it = playerHandler.players.find(static_cast<int>(playerId));
            return it == playerHandler.players.end() || it->second == nullptr
                ? InvalidProvinceId : it->second->homeProvinceId;
        }
        ProvinceId GetLocalProvinceId() const { return GetPlayerProvinceId(localPlayerId); }
        ProvinceId GetLocalActiveProvinceId() const
        {
            const auto it = playerHandler.players.find(localPlayerId);
            return it == playerHandler.players.end() || it->second == nullptr
                ? InvalidProvinceId : it->second->GetActiveProvinceId();
        }
        bool SetLocalActiveProvince(ProvinceId provinceId)
        {
            const auto it = playerHandler.players.find(localPlayerId);
            if (it == playerHandler.players.end() || it->second == nullptr ||
                !it->second->SetActiveProvince(provinceId))
                return false;

            // Province selection is presentation state. Force the cached world
            // layers to sample the newly selected map even when the camera and
            // simulation tick have not changed (notably while paused).
            if (TileMap* map = it->second->GetTileMap(provinceId); map != nullptr)
            {
                map->terrainDirty = true;
                map->buildingsDirty = true;
            }
            cachedCameraTarget = {std::numeric_limits<float>::max(),
                                  std::numeric_limits<float>::max()};
            cachedCameraZoom = -1.0f;
            return true;
        }
        std::size_t GetColonizationOperationCount() const
        {
            return pendingColonizations.size();
        }
        bool IsColonizationInProgress(ProvinceId targetProvinceId) const
        {
            return pendingColonizations.contains(targetProvinceId);
        }
        std::optional<ColonizationProgressView> GetColonizationProgress(
            ProvinceId targetProvinceId) const;
        WorldJourneySystem& GetArmyJourneySystem() { return armyJourneySystem; }
        const WorldJourneySystem& GetArmyJourneySystem() const { return armyJourneySystem; }
        BattleLifecycleSystem& GetBattleSystem() { return battleSystem; }
        const BattleLifecycleSystem& GetBattleSystem() const { return battleSystem; }
        const std::map<std::uint64_t, TradeOrder>& GetActiveTradeOrders() const
        {
            return activeTradeOrders;
        }
        ProvinceEventSystem& GetEventSystem() { return eventSystem; }
        const ProvinceEventSystem& GetEventSystem() const { return eventSystem; }
        const PlayerState* FindPlayerState(PlayerId playerId) const
        {
            const auto it = playerHandler.players.find(static_cast<int>(playerId));
            return it == playerHandler.players.end() || it->second == nullptr
                ? nullptr : static_cast<const PlayerState*>(it->second.get());
        }
        // Returns the player controlled by local UI.
        int GetLocalPlayerId() const { return localPlayerId; }
        // Compatibility query for local placement. Local province maps are
        // fully visible in the campaign rework, so every valid footprint is
        // considered visible; the renderer's soft mask is not consulted.
        bool IsBuildFootprintVisibleToPlayer(int playerId, Vec2i anchor, Vec2i footprint) const;
        // Returns the authoritative simulation tick counter.
        std::uint64_t GetSimulationTick() const { return simulationTick; }
        // Generation status for callers that need to avoid starting a session
        // after a bounded layout failure.
        bool IsInitialized() const { return initialized; }
        const std::string& GetInitializationError() const { return initializationError; }
        // Diagnostics for the resource lifecycle audit. These values are
        // derived from world-owned player/building state and are not gameplay
        // inputs.
        std::size_t GetLiveShipmentCount() const;
        int GetStoredResourceUnits() const;
        // ETAP 12.1 — tilemap/playerHandler are private; this is the only access
        // point. Const-qualified callers (e.g. code holding a `const GameWorld&`)
        // get a read-only view; non-const callers still get a mutable one, since
        // TileMap's own accessors (GetBuilding, operator[], ...) aren't const-
        // qualified yet — tightening that is deferred follow-up work (see
        // docs/tech_debt.md). Even so, gameplay state must only
        // be MUTATED through GameCommand (ProcessCommands) or persistence; UI code
        // reading through the non-const overload must not write.
        TileMap& GetTileMap()
        {
            auto it = playerHandler.players.find(localPlayerId);
            if (it != playerHandler.players.end() && it->second != nullptr &&
                it->second->GetTileMap() != nullptr)
                return *it->second->GetTileMap();
            static TileMap emptyMap;
            return emptyMap;
        }
        const TileMap& GetTileMap() const
        {
            const auto it = playerHandler.players.find(localPlayerId);
            if (it != playerHandler.players.end() && it->second != nullptr &&
                it->second->GetTileMap() != nullptr)
                return *it->second->GetTileMap();
            static const TileMap emptyMap;
            return emptyMap;
        }
        TileMap* GetTileMapForPlayer(PlayerId playerId)
        {
            const auto it = playerHandler.players.find(static_cast<int>(playerId));
            return it == playerHandler.players.end() || it->second == nullptr
                       ? nullptr : it->second->GetTileMap();
        }
        const TileMap* GetTileMapForPlayer(PlayerId playerId) const
        {
            const auto it = playerHandler.players.find(static_cast<int>(playerId));
            return it == playerHandler.players.end() || it->second == nullptr
                       ? nullptr : it->second->GetTileMap();
        }
        PlayerHandler& GetPlayerHandler() { return playerHandler; }
        const PlayerHandler& GetPlayerHandler() const { return playerHandler; }
        PlayerHandler& GetPlayerHandlerForTesting() { return playerHandler; }

    private:
        // Generates terrain, HQ anchors and a valid starting-settlement plan
        // for `playerCount` players. A bounded deterministic retry changes
        // the seed when terrain or starting-settlement validation fails.
        // This runs before any Player/Building exists, so a retry only
        // regenerates the tilemap. A failed result never represents a
        // playable map.
        struct WorldLayoutResult
        {
            bool success{false};
            WorldLayoutFailure failure{WorldLayoutFailure::None};
            Vec2i hqFootprint{};
            std::vector<Vec2i> anchors;
            unsigned int requestedSeed{0};
            unsigned int finalSeed{0};
            int attempts{0};
            std::string failureReason;
        };
        WorldLayoutResult GenerateWorldLayout(TileMap& map, MapParameters& params, int playerCount);
        // Creates one player and initializes display/controller metadata.
        Player* CreatePlayer(int id, PlayerControllerType controllerType, const std::string& name, Color color,
                             TileMap& map);
        // Places just the Headquarters and clears its starting area.
        // Returns the clamped HQ anchor actually used.
        Vec2i CreateStartingHq(Player* player, Vec2i hqAnchor, unsigned int seed, TileMap& map);
        // Places the village, its start road to the HQ, and the starting
        // resource patches.
        void CreateStartingVillageAndResources(Player* player, Vec2i hqAnchor, unsigned int seed,
                                               TileMap& map);
        // Attaches the right controller implementation for one player.
        void AttachControllerForPlayer(Player* player);
        // Advances all input/AI/network controllers.
        void UpdateControllers(double dt);
        void UpdateOwnedProvinceSimulations(double dt);
        void UpdateColonizationOperations();
        void ProcessNonBattleJourneyEvents();
        void ProcessResourceTransfers();
        void ProcessArmyTransfers();
        void ProcessTradeOrders();
        void UpdateBattles();
        struct ColonizationOperation;
        // Executes every queued command in submission order.
        void ProcessCommands();
        // Validates and applies one command to the simulation.
        bool ExecuteCommand(const GameCommand& command);
        // Recomputes current visibility from owned buildings.
        // Derived state is intentionally rebuilt after load/snapshot rather than
        // serialized as a visual texture or GPU resource.
        void UpdateFogOfWar();
        void RebindMovedState();
        bool InitializeGlobalCampaign(int playerCount,
                                      const GlobalMapGenerationParameters& parameters);
        bool InitializeGlobalCampaign(int playerCount, std::uint32_t seed);
        bool BindPlayersToGlobalCampaign();
        bool CompleteColonization(const ColonizationOperation& operation);
        bool CompleteAutomaticColonization(Player& player, ProvinceId targetProvinceId);
        bool SaveToStream(std::ostream& out) const;
        bool LoadFromStream(std::istream& in, Renderer* renderer, int localPlayerIdOverride);
    
    public:
        Renderer*     render{nullptr};
        std::string worldName{"default"};
        int localPlayerId{0};

    private:
        GlobalMap globalMap;
        CampaignGenerationParameters campaignGenerationParameters{};
        WorldJourneySystem armyJourneySystem;
        BattleLifecycleSystem battleSystem;
        ProvinceEventSystem eventSystem;
        // Home provinces are generated before runtime Player objects exist.
        // This short-lived map is discarded once players are bound; the
        // durable global state is the PlayerState base owned by each Player.
        std::map<PlayerId, ProvinceId> pendingHomeProvinceByPlayer;
        struct ColonizationOperation
        {
            PlayerId playerId{InvalidPlayerId};
            ProvinceId sourceProvinceId{InvalidProvinceId};
            ProvinceId targetProvinceId{InvalidProvinceId};
            WorldJourneyId journeyId{InvalidWorldJourneyId};
            ColonizationPhase phase{ColonizationPhase::Traveling};
            std::uint64_t phaseCompletionTick{0};
            std::uint64_t settlementDurationTicks{0};
            std::vector<ColonizationCost> cost;
        };
        std::map<ProvinceId, ColonizationOperation> pendingColonizations;
        // Authoritative trade orders remain here until the cargo is unloaded
        // into the origin province. The city and journey are separate domain
        // objects, so this ledger is the join point used by update, save and
        // checksum code.
        std::map<std::uint64_t, TradeOrder> activeTradeOrders;
        std::uint64_t nextTradeOrderId{1};
        static constexpr std::size_t MaxActiveTradeOrders = 256;
        PlayerHandler playerHandler;
        std::deque<GameCommand> pendingCommands;
        std::vector<GameCommandResult> commandResults;
        std::vector<std::unique_ptr<IController>> controllers;
        std::uint64_t nextCommandId{1};
        std::uint64_t simulationTick{0};
        bool initialized{false};
        std::string initializationError;
        Vec2f cachedCameraTarget{std::numeric_limits<float>::max(), std::numeric_limits<float>::max()};
        float cachedCameraZoom{-1.0f};
};

// Resolves build payment from authoritative world state only. A command never
// carries a price, construction shortcut, or permission bit.
BuildPaymentPolicy ResolveBuildPaymentPolicy(const GameWorld& world, const Player& player);


#endif
