#ifndef GAMEWORLD_H
#define GAMEWORLD_H

#include "core/Types.h"
#include "core/FogOfWar.h"
#include "ai/Controller.h"
#include "core/GameCommand.h"
#include "core/GameSnapshot.h"
#include "simulation/MapGenerator.h"
#include "simulation/MilitaryRoadNetwork.h"
#include "simulation/PathingService.h"
#include "economy/Player.h"
#include "ui/Renderer.h"
#include "warfare/BattleUnit.h"
#include "warfare/CombatPipeline.h"
#include "warfare/CombatTelemetry.h"

class AudioSystem;

enum class BuildPaymentPolicy
{
    ChargeAuthoritativeCost,
    FreeDebugHuman
};

#include <cstdint>
#include <deque>
#include <iosfwd>
#include <string_view>
#include <utility>
#include <vector>

class PlayerHandler
{
    public:
        PlayerHandler() = default;

        // Owns all players participating in the current world.
        std::map<int, std::unique_ptr<Player>> players;
};

// Owns the playable simulation state, including map, players and persistence.
class GameWorld
{
    public:
        GameWorld() = default;
        GameWorld(const GameWorld&) = delete;
        GameWorld& operator=(const GameWorld&) = delete;
        GameWorld(GameWorld&&) noexcept = default;
        GameWorld& operator=(GameWorld&&) noexcept = default;

        // Creates a new world with generated terrain and starting entities.
        // Returns false when bounded world generation cannot produce a valid
        // layout. In that case no playable session is started.
        bool InitWorld(std::string, Renderer*, AudioSystem* audio = nullptr, MapParameters params = {});
        // Creates a deterministic multiplayer world with server-assigned player slots.
        bool InitMultiplayerWorld(std::string name, Renderer* renderer, AudioSystem* audio, MapParameters params, int localPlayerId, bool authoritativeHost);
        // Writes the current world state to a save file.
        bool SaveToFile(const std::string& path) const;
        // Rebuilds the world state from a save file.
        bool LoadFromFile(const std::string& path, Renderer* renderer, AudioSystem* audio = nullptr);
        // Canonical full simulation state used by multiplayer initial sync and
        // recovery. Unlike GameSnapshot, this includes gameplay state rather
        // than only render data.
        std::string SerializeSimulationState() const;
        // Restores a state emitted by SerializeSimulationState. The optional
        // local-player override keeps the receiving client's UI/controller
        // ownership local while retaining the host's authoritative world.
        bool RestoreSimulationState(std::string_view payload, int localPlayerIdOverride = -1);
        // Queues an intent generated by a human, AI or remote player.
        std::uint64_t SubmitCommand(const GameCommand& command);
        // Queues an intent and assigns an authoritative target tick when needed.
        std::uint64_t SubmitCommand(const GameCommand& command, std::uint64_t minimumTargetTick);
        // Returns command accept/reject results emitted since the last consume.
        std::vector<GameCommandResult> ConsumeCommandResults();
        // Applies a command received from an authoritative host to a client-side mirror.
        bool ApplyAuthoritativeCommand(const GameCommand& command);
        // Advances the simulation by elapsed time in seconds.
        void Update(double);
        // Advances only authoritative gameplay state, without touching visual layers.
        void UpdateSimulation(double dt);
        // Draws terrain, roads, buildings and territory overlays.
        void DrawMap();
        // Captures render-safe world state for another thread.
        GameSnapshot BuildSnapshot() const;
        // Computes a deterministic low-cost gameplay checksum for mirror validation.
        std::uint64_t BuildChecksum() const;
        // Bounded AI diagnostics for failed harness scenarios; not simulation state.
        std::string GetAITrace(int playerId) const;
        // Returns the player controlled by local UI.
        int GetLocalPlayerId() const { return localPlayerId; }
        // True when a player's Headquarters has been captured (player eliminated).
        bool IsPlayerDefeated(int playerId) const;
        // Id of the sole surviving player once every other has been eliminated
        // (a decided game); -1 while two or more players remain. Deterministic.
        int GetVictorPlayerId() const;
        // Returns whether every tile of a proposed footprint is currently
        // revealed to this player by deterministic gameplay fog sources.
        // The renderer's soft mask is deliberately not consulted here.
        bool IsBuildFootprintVisibleToPlayer(int playerId, Vec2i anchor, Vec2i footprint) const;
        // TD(etap-6.3): eliminates a player whose HQ has fallen — flags them
        // defeated, clears their deployed units/roster/spawn queues,
        // transfers their production buildings to the conqueror with a
        // productivity ramp (ConqueredEconomy), and drains their storage
        // (conqueror keeps HqComponent::captureStockFraction of each
        // resource, the rest is lost). Called from HqCombatSystem the tick
        // an HQ's currentHp reaches 0. A no-op if defeatedPlayerId is already
        // defeated (idempotent against being invoked more than once).
        void EliminatePlayer(int defeatedPlayerId, int conquerorPlayerId);
        // Returns the authoritative simulation tick counter.
        std::uint64_t GetSimulationTick() const { return simulationTick; }
        // Generation status for callers that need to avoid starting a session
        // after a bounded layout failure.
        bool IsInitialized() const { return initialized; }
        const std::string& GetInitializationError() const { return initializationError; }
        // Diagnostics for the resource lifecycle audit. These values are
        // derived from world-owned player/building state and are not gameplay
        // inputs.
        std::size_t GetLiveShipmentCount() const;
        int GetStoredResourceUnits() const;
        // Returns the global pathfinding service (ETAP 3.4 integration point)
        PathingService* GetPathingService() const { return pathingService.get(); }

        // ETAP 12.1 — tilemap/playerHandler are private; this is the only access
        // point. Const-qualified callers (e.g. code holding a `const GameWorld&`)
        // get a read-only view; non-const callers still get a mutable one, since
        // TileMap's own accessors (GetBuilding, operator[], ...) aren't const-
        // qualified yet — tightening that is deferred follow-up work (see
        // docs/tech_debt.md). Even so, gameplay state must only
        // be MUTATED through GameCommand (ProcessCommands) or persistence; UI code
        // reading through the non-const overload must not write.
        TileMap& GetTileMap() { return tilemap; }
        const TileMap& GetTileMap() const { return tilemap; }
        PlayerHandler& GetPlayerHandler() { return playerHandler; }
        const PlayerHandler& GetPlayerHandler() const { return playerHandler; }
        // Immutable HQ-ring military road network (TD etap-2).
        MilitaryRoadNetwork& GetMilitaryRoads() { return militaryRoads; }
        const MilitaryRoadNetwork& GetMilitaryRoads() const { return militaryRoads; }
        // TD(etap-4): deployed (marching/fighting/arrived) BattleUnit instances,
        // keyed by instanceId across every player (ids are already globally
        // unique — see Player::nextUnitInstanceId). Advanced by
        // UnitMarchSystem::Update, called from UpdateSimulation.
        std::map<int, BattleUnit>& GetDeployedUnits() { return deployedUnits; }
        const std::map<int, BattleUnit>& GetDeployedUnits() const { return deployedUnits; }
        // FIFO of unit instance ids waiting for their column's gate tile to
        // free up, keyed by (fromPlayerId, toPlayerId) marching direction.
        std::map<std::pair<int, int>, std::deque<int>>& GetSpawnQueues() { return spawnQueues; }
        const std::map<std::pair<int, int>, std::deque<int>>& GetSpawnQueues() const { return spawnQueues; }
        // TD(etap-7.2): in-flight tower projectiles (homing AttackEmissions),
        // keyed by an id from AllocateProjectileId(). Persisted in simulation
        // state so recovery snapshots preserve an in-flight tower attack.
        std::map<int, AttackEmission>& GetProjectiles() { return projectiles; }
        const std::map<int, AttackEmission>& GetProjectiles() const { return projectiles; }
        int AllocateProjectileId() { return nextProjectileId++; }
        CombatTelemetry& GetCombatTelemetry() { return combatTelemetry; }
        const CombatTelemetry& GetCombatTelemetry() const { return combatTelemetry; }
        // Mutable escape hatch for tests that construct simulation objects
        // directly (e.g. a standalone Player) — same object as GetTileMap(),
        // named separately so call sites make the intent explicit.
        TileMap& GetTileMapForTesting() { return tilemap; }
        PlayerHandler& GetPlayerHandlerForTesting() { return playerHandler; }

    private:
        // B5 (docs/work_plan_2026-07-13.md): generates terrain, HQ anchors
        // (B1) and the military road ring (B2) for `playerCount` players,
        // retrying with a deterministically perturbed seed (up to a bounded
        // attempt count) if the resulting ring or starting-village layout
        // fails validation. Entirely before any Player/Building exists, so a
        // retry never needs to undo player-visible state — each attempt just
        // regenerates the tilemap terrain and ring from scratch. Returns the
        // (fixed) HQ footprint and the accepted anchors (one per player id
        // 0..playerCount-1). A failed result never represents a playable map.
        struct WorldLayoutResult
        {
            bool success{false};
            Vec2i hqFootprint{};
            std::vector<Vec2i> anchors;
            unsigned int requestedSeed{0};
            unsigned int finalSeed{0};
            int attempts{0};
            std::string failureReason;
        };
        WorldLayoutResult GenerateWorldLayout(MapParameters& params, int playerCount);
        // Creates one player and initializes display/controller metadata.
        Player* CreatePlayer(int id, PlayerControllerType controllerType, const std::string& name, Color color);
        // Places just the Headquarters (and clears its starting area) — must
        // run BEFORE the military road is generated, so the road's
        // impassable-rectangle fallback can never land on a not-yet-built HQ.
        // Returns the clamped HQ anchor actually used.
        Vec2i CreateStartingHq(Player* player, Vec2i hqAnchor, unsigned int seed);
        // Places the village, its start road to the HQ, and the starting
        // resource patches — must run AFTER the military road is generated,
        // so TileMap::CanBuildFootprint's existing isMilitaryRoad check keeps
        // all of this off the road automatically.
        void CreateStartingVillageAndResources(Player* player, Vec2i hqAnchor, unsigned int seed);
        // Attaches the right controller implementation for one player.
        void AttachControllerForPlayer(Player* player);
        // Advances all input/AI/network controllers.
        void UpdateControllers(double dt);
        // Executes every queued command in submission order.
        void ProcessCommands();
        // Validates and applies one command to the simulation.
        bool ExecuteCommand(const GameCommand& command);
        // Advances deployed BattleUnit marching/spawning (TD etap-4). Thin
        // delegator (GameWorld.Units.cpp) to UnitMarchSystem::Update.
        void UpdateUnits(double dt);
        // Recomputes current visibility from owned buildings and deployed units.
        // Derived state is intentionally rebuilt after load/snapshot rather than
        // serialized as a visual texture or GPU resource.
        void UpdateFogOfWar();
        void RebindMovedState();
        bool SaveToStream(std::ostream& out) const;
        bool LoadFromStream(std::istream& in, Renderer* renderer, AudioSystem* audio,
                            int localPlayerIdOverride);
    
    public:
        Renderer*     render{nullptr};
        AudioSystem*  audio{nullptr};
        std::string worldName{"default"};
        int localPlayerId{0};

    private:
        TileMap tilemap;
        PlayerHandler playerHandler;
        MilitaryRoadNetwork militaryRoads;
        std::map<int, BattleUnit> deployedUnits;
        std::map<std::pair<int, int>, std::deque<int>> spawnQueues;
        std::map<int, AttackEmission> projectiles;
        std::map<int, FogOfWarState> fogOfWarByPlayer;
        CombatTelemetry combatTelemetry;
        int nextProjectileId{1};
        std::deque<GameCommand> pendingCommands;
        std::vector<GameCommandResult> commandResults;
        std::vector<std::unique_ptr<IController>> controllers;
        std::unique_ptr<PathingService> pathingService;
        std::uint64_t nextCommandId{1};
        std::uint64_t simulationTick{0};
        bool initialized{false};
        std::string initializationError;
        Vec2f cachedCameraTarget{std::numeric_limits<float>::max(), std::numeric_limits<float>::max()};
        float cachedCameraZoom{-1.0f};
};

// Resolves build payment from authoritative world state only. A command never
// carries a price, construction shortcut, or permission bit.
BuildPaymentPolicy ResolveBuildPaymentPolicy(const GameWorld& world, const Player& player);


#endif
